version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Build completed

  post_build:
    commands:
      - echo "Zipping application..."
      - zip -r app.zip .

      - echo "Uploading to S3..."
      - aws s3 cp app.zip s3://poc22-bucket123/app.zip
      
